services:
  db_resource:
    container_name: "db_resource"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "13306:3306"
    volumes:
      - "./scripts/mysql_prepare_resource.sql:/docker-entrypoint-initdb.d/1.sql"

  db_song:
    container_name: "db_song"
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "23306:3306"
    volumes:
      - "./scripts/mysql_prepare_song.sql:/docker-entrypoint-initdb.d/1.sql"

