networks:
  mikro:
    driver: bridge

services:
  # Resource service
  sc_resource:
    container_name: sc_resource
    build: resource_service
    environment:
      SC_RESOURCE_PORT: "${SC_RESOURCE_PORT}"
      SC_RESOURCE_DB_HOST: db_resource
      SC_RESOURCE_DB_PORT: 3306 # default mysql port
      SC_SONG_URL: "${SC_RESOURCE_SONG_HOSTNAME_ALIAS}:${SC_SONG_PORT}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SC_DB_RETRY_COUNT: 15
    links:
      - db_resource
      - "sc_song:${SC_RESOURCE_SONG_HOSTNAME_ALIAS}" # Why an alias? I had an error when passing "sc_song" to the URI java constructor (weird).
                                                     # What's more interesting, the creation of the same URI object worked well in the `jshell`.
                                                     # So I removed underscore here, and it works as expected.
    ports:
      - "${SC_RESOURCE_PORT}:${SC_RESOURCE_PORT}"
    networks:
      - mikro
    depends_on:
      db_resource:
        condition: service_started

  # Database that contains resource data, used by the resource service
  db_resource:
    container_name: db_resource
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "./scripts/mysql_prepare_resource.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - mikro

  # Song service
  sc_song:
    container_name: sc_song
    build: song_service
    environment:
      SC_SONG_PORT: "${SC_SONG_PORT}"
      SC_SONG_DB_HOST: db_song
      SC_SONG_DB_PORT: 3306 # default mysql port
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      SC_DB_RETRY_COUNT: 15
    links:
      - db_song
    ports:
      - "${SC_SONG_PORT}:${SC_SONG_PORT}"
    networks:
      - mikro
    depends_on:
      db_song:
        condition: service_started

  # Database that contains songs data, used by the song service
  db_song:
    container_name: db_song
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - "./scripts/mysql_prepare_song.sql:/docker-entrypoint-initdb.d/1.sql"
    networks:
      - mikro

